### ISSUE TITLE
Question on interface to posgresql

### ISSUE THREAD

**Issue by TacHuynh** [dvjdjvu/hdbpp#2]
My back end is timescaledb/posgres instead of mysql.
Do I need to include a python connector for posgresql instead of "import mysql.connector" in order for this code to work?
Thanks,
Tac.

**Comment by dvjdjvu** [comment]
Now I have a problem, after fix error I have forgotten include code for postgres. I will fix it.

**Comment by dvjdjvu** [comment]
I have returned postgresql, but I didnt check it. If you will be first write me.

**Comment by TacHuynh** [comment]
Thanks,
So far no problem.
Tac.
